package com.example.daftarkucing;

import java.util.ArrayList;

public class KucingData {
    public static String[][] data = new String[][]{
            {"Abyssinian", "Kucing Abyssinian merupakan kucing domestik berbulu pendek, yang dinamai dari kota Abyssinia, Ethiopia. Awalnya mereka berasal dari Ethiopia, namun studi menunjukkan mereka berasal dari Mesir, dan mereka merupakan salah satu kucing dari Pharaoh. Kucing ini diketahui dipopulerkan pada tahun 1871, memenangkan juara ketiga pada Crystal Palace Cat Show.","https://meowcitizen.com/wp-content/uploads/2018/09/meowcitizen_jenis-kucing-lengkap-1-abyssinian.jpg","Ciri khas yang dikenal selain bulunya yang cenderung tipis dan telinganya yang terlihat besar adalah kucing ini merupakan salah satu kucing yang cerdas. Abyssinian cenderung sangat aktif, suka bermain, dan bahkan bisa dilatih untuk melakukan cat tricks sehingga bukan hal aneh apabila kamu berminat untuk mengajaknya jalan-jalan menggunakan tali di badannya layaknya seekor anjing. Mungkin pada awalnya mereka cenderung waspada dan pemalu terhadap orang yang tidak dia kenal. Akan tetapi, apabila kucing ini sudah percaya dengan orang sekitar dan pemiliknya, kucing ini merupakan kucing keluarga yang sangat menyenangkan karena sifat alamiahnya yang suka bermain dan penyayang terhadap sekitarnya."},
            {"Aegean","Aegean merupakan satu-satunya jenis kucing alamiah yang berasal dari Yunani. Maksudnya, kucing ini berkembang tanpa adanya interferensi manusia sama sekali. Mereka mendapatkan namanya dari Laut Aegean. Meski sudah merupakan kucing domestik, Aegean baru mendapatkan pengakuan pada tahun 1990.","https://meowcitizen.com/wp-content/uploads/2018/09/meowcitizen_jenis-kucing-lengkap-2-aegean.jpg","Aegean memiliki ciri khas bulu yang pendek dan tubuh yang cenderung berotot. Pasti sekilas kamu berpikir “wah, seperti kucing kampung ya” dan itu tidak salah juga. Kucing ini terdapat banyak di tempat asalnya itu sendiri yaitu Yunani, namun tidak begitu banyak tersebar diluar itu. Aegean merupakan salah satu jenis kucing tertua yang alamiah, bukan melalui persilangan antar ras lainnya yang menjadikan dia terbebas dari kelainan genetik.Tidak banyak yang memelihara dia diluar negara asalnya. Akan tetapi di Yunani itu sendiri banyak yang memelihara Aegean dan beberapa masih hidup liar juga di jalan. Kucing Aegean liar bertahan hidup melalui kemampuan alamiahnya dalam berburu maupun diberi makan oleh nelayan setempat. Meski terlihat independen, kucing Aegean sangatlah menyukai interaksi dengan manusia dan bahkan anak kecil."},
            {"Arabian Mau","Arabian Mau sudah ada di semenanjung Arab untuk lebih dari 1000 tahun. Kucing padang pasir ini sudah ada di jalan-jalan Kuwait, Omar, Qatar, Uni Emirat Arab dan Saudi Arabia. Kalau kamu jalan-jalan ke negara timur tengah tersebut, kamu pasti akan tidak asing dengan mereka. Meski sudah berumur lama, hanya baru-baru ini saja jenis kucing ini diakui.","https://meowcitizen.com/wp-content/uploads/2018/09/meowcitizen_jenis-kucing-lengkap-8-arabian-mau.jpg","Kucing ini sangat terbiasa dengan suhu panas, karena kucing ini merupakan pemburu alami dan terbiasa dengan gaya hidup di padang pasir. Kucing ini cenderung kalem dan hanya mengeong ketika ada maunya (i.e. meminta makan). Mereka suka bermain dan cenderung aktif. Mereka juga tidak sulit dan memilih-milih makanan, karena mereka cenderung suka makan. Akan tetapi, kucing ini bersifat territorial dimana biasanya kucing jantan akan menjaga teritori mereka dari kucing jantan lainnya."},
            {"Asian- Malayan","Sering juga disebut sebagai Malaya, meskipun namanya Asian-Malayan tetapi sebenarnya dia berasal dari United Kingdom. Kucing ini merupakan persilangan antara kucing Burmese dan Cinchilla sehingga karakteristik antara Malayan dan Burmese sangatlah mirip.","https://meowcitizen.com/wp-content/uploads/2018/09/meowcitizen_jenis-kucing-lengkap-9-asian-malayan.jpg","Malayan memiliki karakteristik fisik tubuhnya yang relatif berotot, kaki yang langsing, serta bulu yang bisa lebat maupun berbulu pendek. Malayan tergolong kucing yang aktif, dia senang bermain, bereksplorasi di dalam rumah, dan dapat berinteraksi sosial dengan manusia dengan sangat baik. Meski sangat baik dalam itneraksinya, kucing Malayan tidak perlu keluar rumah, mereka bisa berlama-lama di dalam rumah bahkan tidak perlu keluar rumah sama sekali. Mereka juga tergolong sangat vokal, jadi perlu diperhatikan, ya! Jika orang rumah tidak suka kucing berisik."},
            {"Bengal","Kucing favorit bagi pecinta hewan eksotis, Bengal memiliki corak khusus seperti kucing hutan liar. Meski begitu, Bengal merupakan persilangan kucing Asian Leopard (kucing liar) dan kucing domestik.","https://meowcitizen.com/wp-content/uploads/2018/09/meowcitizen_jenis-kucing-lengkap-14-bengal.jpg","Ciri khas yang tentu membuat orang-orang tertarik adalah coraknya yang menjadikannya terlihat seperti leopard dan macan, bentuk tubuhnya yang langsing dan cenderung berotot, serta ukuran tubuhnya yang menjadikannya masuk kedalam klasifikasih kucing besar dengar berat sekitar 4-8kg. Kucing Bengal mungkin agak menantang diawal apabila kamu berniat mengadopsinya, mereka sangatlah aktif, dan ketika bosan mereka cenderung dekstruktif yaitu memainkan barang-barang hingga rusak ataupun terjatuh. Mereka juga perlu tempat vertikal seperti pohon ataupun tempat tempat memanjat lainnya. Oleh karena itu, sebaiknya beri mereka kebutuhan sosial yang cukup seperti bermain dengannya, berikan teman kucing/anjing yang lainnya. Mereka juga relatif pintar dan sering melakukan sesuatu untuk mendapatkan perhatian pemiliknya. Jadi, pastikan kamu bisa memenuhi kebutuhan spesial kucing ini ya!"},
            {"Birman","Birman merupakan jenis kucing yang berasal dari Perancis, meskipun masih belum diketahui persis darimana asal muasalnya. Birman memiliki mata biru yang sangat cantik sebagai karakteristik uniknya.","https://meowcitizen.com/wp-content/uploads/2018/09/meowcitizen_jenis-kucing-lengkap-15-birman.jpg","Birman memiliki corak khusus di wajahnya seperti Siamese dan Balinese, dengan perbedaan yaitu pada matanya dan gradasi warna pada tubuhnya. Warna dominan pada kucing Birman berada pada ‘ujung’ tubuhnya seperti tangan, kaki, telinga dan ekornya. Birman memiliki suara meong yang sangat lembut, dan cenderung kalem, tidak seperti Siamese. Dia sangat menempel dengan pemiliknya dan secara umum selalu ingin mengikuti kemanapun pemiliknya pergi. Dia juga sangat penasaran dan suka mengeksplor tempat-tempat aneh dirumahnya. Jadi perhatikan terus ya, dia dimana. Jangan sampai dia keluar rumah tapi kamu tidak sadar."},
            {"Cheetoh","‘Cheetah’ imut ini merupakan salah satu jenis kucing baru dan masih experimental, pertama kali dikenalkan pada tahun 2003 oleh hasil persilangan antara kucing Bengal dan kucing Ocicat.","https://meowcitizen.com/wp-content/uploads/2018/09/meowcitizen_jenis-kucing-lengkap-27-cheetoh.jpg","Cheetoh memiliki ciri khas yang seperti Cheetah, yaitu memili corak hitam di seluruh tubuhnya. Ciri fisik lainnya adalah kepalanya yang agak runcing, mata yang cenderung kecil, kuping yang mengarah keluar, serta ekornya yang pendek. Meski kelihatannya galak, Cheetoh lebih jinak daripada moyang genetiknya yaitu Bengal. Cheetoh sangat bersahabat dan seperti Bengal, bisa dilatih dan apaabila dibiasakan, mereka dapat dengan mudah dan menyukai berjalan-jalan di luar sambil diikat di bagian tubuhnya."},
            {"Dragon Li","Kucing yang satu ini merupakan kucing alamiah dari China, bukan hasil persilangan dengan ras kucing lainnya. Berdasarkan buku-buku kuno, kucing ini sudah ada sejak lama, berabad-abad yang lalu, namun baru belakangan ini dia diakui sebagai salah satu jenis kucing ras.","https://meowcitizen.com/wp-content/uploads/2018/09/meowcitizen_jenis-kucing-lengkap-33-dragon-li.jpg","Kucing ini memiliki ciri khas corak tabby yaitu corak yang seperti loreng, umumnya warna hitam dan abu-abu. Li memiliki telinga yang menonjol dan tajam, serta tubuhnya relatif berotot. Meskipun banyak kucing yang sekilas mirip dengan Li ini, mereka tidak mudah ditemukan diluar China. Kucing ini memiliki sifat cerdas, aktif, dan bersahabat dengan manusia. Namun jangan salah, mereka merupakan pemburu yang sangat hebat, tidak hanya berburu tikus besar. Konon, mereka juga pernah dilatih bisa untuk mengambil koran dan mengantarkannya ke majikannya."},
            {"FoldEx","Foldex merupakan singkatan dari Exotic Fold, yang merupakan campuran dari kucing Scottish Fold dan kucing Exotic Shorthair. Kucing ini dikembangbiakkan di Quebec, Kanada, pada awal 90an. Kucing ini sangatlah menggemaskan dan oleh karena itu seringkali kucing ini disamakan dengan sebuah boneka Teddy Bear.","https://meowcitizen.com/wp-content/uploads/2018/09/meowcitizen_jenis-kucing-lengkap-37-foldex.jpg","Foldex sekilas memiliki kesamaan bentuk tubuh dengan Exotic shorthair, badan yang bulat namun dengan struktur tulang yang kuat, dan wajah yang bulat dan menggemaskan.Ciri khas yang paling menonjol adalah telinganya yang terlipat, dan kaki-kakinya yang pendek layaknya kucing Scottish Fold. Kucing ini dikenal dengan sifatnya yang aktif, penasaran, dan bersahabat. Dia tidak ragu-ragu untuk mendekati orang asing dan sangat suka untuk dielus-elus."},
            {"Himalayan Cat","Himalaya, atau singkatnya dipanggil Himmie, merupakan hasil persilangan dari kucing Persia dan Siamese. Himalayan dianggap sub-jenis dari kucing persia daripada kucing Siamese.","https://meowcitizen.com/wp-content/uploads/2018/09/meowcitizen_jenis-kucing-lengkap-41-himalayan.jpg","Bulu lebat, berwarna putih dan memiliki gradasi hitam di wajah dan kaki-tangannya, merupakan ciri dari kucing Himalaya. Dia mendapatkan genetik bulu lebatnya dari Persian, dan gradasi bulu serta mata biru yang cantiknya dari Siamese.Mereka memiliki sifat yang cenderung kalem, suka bermain karena genetik Siamesenya, dan penyayang terhadap pemiliknya. Mereka merupakan kucing yang lebih baik dipelihara di dalam rumah saja, karena mereka bukan tipe yang akan terbiasa dengan lingkungan yang ramai, dan mereka bukan kucing yang suka berkelahi. Oleh karena itu, sangat berbahaya jika mereka dibiarkan bebas keluar rumah karena rentan diserang oleh hewan atau kucing lain."}
    };

    public static ArrayList<Kucing> getListData(){
        Kucing kucing = null;
        ArrayList<Kucing> list = new ArrayList<>();
        for (String[] aData : data){
            kucing = new Kucing();
            kucing.setName(aData[0]);
            kucing.setRemarks(aData[1]);
            kucing.setPhoto(aData[2]);
            kucing.setDetail(aData[3]);

            list.add(kucing);
        }

        return list;
    }
}
